### ISSUE TITLE
How to change height of sheet after updated content size of view?

### ISSUE THREAD

**Issue by khushabu29** [gordontucker/FittedSheets#123]
If the content size of the view controller's view gets changed while the sheet is opened for any reason for example label text gets updated to 3 lines from 1 line, then the sheet height does not get resized (does not increase or decrease the height of the sheet). In fact, some content gets shrink as shown in the screenshot. 

![IMG_6CCB7D3C221E-1](https://user-images.githubusercontent.com/11438647/101475347-4d3f9680-3972-11eb-846f-0ea0ff9f441a.jpeg)

**Comment by ArlindDushi** [comment]
Hey @gordontucker
Thanks for the amazing library. I also have a case in my app where content gets resized after the viewcontroller is already presented, so can this be achieved with the current version or does it need extra implementation?

**Comment by jerometonnelier** [comment]
Same issue here with some dynamic content. It's an awesome library btw ;-)
@ArlindDushi  @khushabu29  did you manage to update the size of the presented controller? I tried to invalidate various contentSizes, but no luck so far either. I use on [.intrinsic] as options.
Thanks

**Comment by BradPatras** [comment]
Ran into this same issue when updating the sheet content after initial view load.  The function that does the trick is in `SheetContentViewController.swift`. The function `updatePreferredHeight()` will recalculate the intrinsic height based on the content.  Unfortunately this function is not `public` so it's inaccessible.  

One way to call that method indirectly is to call `sheetViewController.animateIn()` when the content/height changes. This method technically does quite a few things in addition to recalculating the height but in my case it turned out to be exactly what I needed!

**Comment by jerometonnelier** [comment]
Thanks a lot @gordontucker ;-)

**Comment by ankitagarwal007** [comment]
@gordontucker It is not  working if scrollview is  present
