### ISSUE TITLE
Cannot find 'SheetOptions' in scope problem

### ISSUE THREAD

**Issue by WrathChaos** [gordontucker/FittedSheets#124]
Hello @gordontucker,

Nice library, however I cannot use `SheetOptions`.
It simply does not exist in the pod library as well. I could not even install another version. In my Podfile, I simply add: 

```
  pod 'FittedSheets'
```

Can you help me with that? I really want to use this library.

![CleanShot 2020-12-14 at 8 06 35](https://user-images.githubusercontent.com/6813862/102111854-f5a89b80-3e47-11eb-9403-2353020a0d24.png)

**Comment by gordontucker** [comment]
Either you are targeting a version older than is supporting (and are thus getting a pre 2.0.0 build), or you haven't `import FittedSheets` in your file.

**Comment by WrathChaos** [comment]
I tried to target `2.0.0` and `2.2.3` with: 

```
  pod 'FittedSheets', '~> 2.0.0'
```

**Comment by gordontucker** [comment]
What version of iOS are you targeting. It sounds like you have your target set to an unsupported version.

**Comment by WrathChaos** [comment]
![image](https://user-images.githubusercontent.com/6813862/102614468-56d0b780-4145-11eb-8fb9-f265582268cb.png)

It's 14.2

**Comment by gordontucker** [comment]
I mean in the pod file. `platform :ios, '13.0'` for example.

**Comment by cyphasusu** [comment]
Guys any update on this?
Currently having same issue

**Comment by gordontucker** [comment]
The only way you wouldn't get that is if you have an old iOS target or pod target on the podfile.

**Comment by EDMODJ** [comment]
> Guys any update on this?
> Currently having same issue

If you have iOS Target 11 or lower (in Podfile) CocoaPods installs FittedSheets 1.0 version where SheetOptions is not available

You should target iOS 12.0 (in Podfile) or higher in order to install FittedSheets 2.*.* with SheetOptions available
<img width="345" alt="Screen Shot 2022-03-28 at 19 39 14" src="https://user-images.githubusercontent.com/2740685/160515630-b131c77a-789f-4d10-ba17-24676a1f461d.png">
