### ISSUE TITLE
Pass data to bottom view controller

### ISSUE THREAD

**Issue by billypap1** [gordontucker/FittedSheets#131]
Hello, I have an issue changing values in bottom view controller.
I want to set value of Parent UIViewController to Bottom View Controller's variable when it appears. Is this possible?

**Comment by gordontucker** [comment]
I'm not sure what you want since I don't have anything called bottom view controller. If you mean the view controller that is presenting the sheet view controller, typically you'd use the presentingViewController 
 property as defined here: `https://developer.apple.com/documentation/uikit/uiviewcontroller/1621430-presentingviewcontroller`. If you've tried that and it isn't working, let me know. It might be a bug in my framework at that point.
