### ISSUE TITLE
Allow pulling below the minimum height and bounce back

### ISSUE THREAD

**Issue by mustafaysil** [gordontucker/FittedSheets#132]
First of all, thank you for this useful project.
I using the FittedSheets latest version is 2.0.13 but I can't call the **allowPullingPastMinHeight**. 
I wonder when will be release this feature 
```
/// Default value for allowPullingPastMinHeight. Defaults to true.
public static var allowPullingPastMinHeight = true
/// Allow pulling below the minimum height and bounce back. Defaults to true.
public var allowPullingPastMinHeight = SheetViewController.allowPullingPastMinHeight
```

**Comment by gordontucker** [comment]
I'm not completely clear on what you are asking for. 

Setting that property to false prevents the user from dragging the sheet smaller than the smallest size specified. The "Max Min Height" demo shows what this does when set to false. The default is true, which is why you are able to see the sheet dismissing as you swipe down from the smallest size typically.

**Comment by gordontucker** [comment]
I'm not completely clear on what you are asking for. 

Setting that property to false prevents the user from dragging the sheet smaller than the smallest size specified. The "Max Min Height" demo shows what this does when set to false. The default is true, which is why you are able to see the sheet dismissing as you swipe down from the smallest size typically.

The latest version is 2.3.2, so you should probably update to that since I don't remember exactly what was happening back in 2.0.13.

**Comment by mustafaysil** [comment]
My problem is caused by error in my pod configuration and it works fine.
@gordontucker Thank you for answer
