### ISSUE TITLE
Present FittedSheets from the Top instead of the Bottom

### ISSUE THREAD

**Issue by codedentwickler** [gordontucker/FittedSheets#27]
Please how can I anchor the sheet presented to the top instead of the bottom. I know this is more of a feature request but I will like to know how I can achieve this by modifying the current implementation.

**Comment by gordontucker** [comment]
It wouldn't be super hard to do this in a fork. The biggest part you would have to go through SheetViewController and change the `setUpChildViewController` and `setUpContainerView` to switch the top and bottom pinning. Then change `setUpPullBarView` to attach below the view instead of above it. Last you'd have to change `panned` to check the scroll direction to be the other direction. Once that is done, there might be little changes to get it to look properly (I couldn't say what without making all the above changes) and you'd probably have to adjust the keyboard logic (or just take it out and handle keyboard stuff differently)

**Comment by jordanjanaq** [comment]
Hi, I have a question, how did you manage  panned?
