### ISSUE TITLE
Access Presenting ViewController

### ISSUE THREAD

**Issue by Urkman** [gordontucker/FittedSheets#5]
Is there an option to access the presenting ViewController while the Sheet is displayed?

**Comment by hipwelljo** [comment]
I'm able to get it via `self.presentingViewController` from the view controller inside the sheet view or from the sheet view controller as well.

**Comment by Urkman** [comment]
Sorry, I described it wrong...
I want the user to interact with the presenting ViewController, while the sheet is displayed...
Like the Maps App

**Comment by gordontucker** [comment]
I'll take a look at what it will take to add this.

**Comment by gordontucker** [comment]
It looks like trying to add this would require a completely different solution since I am using modal presentations for this. I am going to close this for now since it isn't really feasable to solve without a rewrite. Maybe in the future I will add a second way to present as an inline child view controller instead of from a window level.
