### ISSUE TITLE
how to dismiss FittedSheets using button ?

### ISSUE THREAD

**Issue by irfanpule** [gordontucker/FittedSheets#50]
if I using `self.dismiss(animated: true, completion: nil)`, I will get different animation. Background (overlay) move to bottom not fade out.

**Comment by i0sa** [comment]
Yup, same thing, it doesnt fade out.

**Comment by i0sa** [comment]
Actually i found the solution for this,
Instead of using dismiss, you can dismiss it like this
`self.sheetViewController?.closeSheet()`

as seen in the example here : https://github.com/gordontucker/FittedSheets/blob/69a402cbe6cc5e8ce26859162fe9400767b89721/FittedSheets/NavigationExample/NavigationRootViewController.swift

**Comment by irfanpule** [comment]
Thanks i will try it

Pada tanggal Min, 3 Nov 2019 17:38, i0sa <notifications@github.com> menulis:

**Comment by 8secz-johndpope** [comment]
@gordontucker  - might be good to have closeSheet() -> just onward call attemptDismiss(animated: true) as a helper. I'm trying to spit out a build and this broke things. all good.
