### ISSUE TITLE
Enhancement - callback on didResize

### ISSUE THREAD

**Issue by johndpope** [gordontucker/FittedSheets#76]
I want to do something to my view after I have swiped up / seems like there's no hooks currently.

**Comment by johndpope** [comment]
thanks Gordon

**Comment by ataravati** [comment]
@johndpope @gordontucker I see that this PR has been merged, but I don't see a `didResize` callback.

**Comment by gordontucker** [comment]
The sizeChanged closure is what you are looking for. You'll find it on SheetViewController

**Comment by ataravati** [comment]
@gordontucker The `sizeChanged` property only gives you two states. In fact, it could've been easily replaced by `stateChanged` with "collapsed" and "expanded" states. Because, the actual size doesn't matter. You set the size when you initialize the sheet so you don't care what the size is when it's fully expanded. 

What is missing here is a `isResizing` so you know when the sheet is being resized. It's not a big deal. I used `viewWillLayoutSubviews` of the sheet content view controller for what I needed, but it would be nice if the sheet had a property that could be used for this purpose.

**Comment by gordontucker** [comment]
Ah, so you wanted something that is called whenever the height is changed, even if it is user dragging around. I can add something like that.

**Comment by ataravati** [comment]
That would be awesome. Thanks!

What I would suggest is event that fires when the sheet starts resizing. That's why I said the size doesn't even matter here. It could be a `stateChanged` property with these states: `expanded`, `collapsed`, `resizing`.
