### ISSUE TITLE
Corner radius is not setting on 1.4.6 version

### ISSUE THREAD

**Issue by abayken** [gordontucker/FittedSheets#85]
I have ViewController with navigation bar that I presented inside SheetViewController. I set `topCornerRadius`, but it has no effect. Also I set `extendBackgroundBehindHandle`, which has also no effect, because there is `UINavigationController`. How to fix it? 
EDIT: I set `extendBackgroundBehindHandle ` to false and it seems corner radius is working. But I need that indicator to be inside not outside. Here is my code: 
```
let sheet = SheetViewController(controller: UINavigationController(rootViewController: FitViewController(nibName: "FitViewController", bundle: nil)), sizes: [.fullScreen])
        sheet.adjustForBottomSafeArea = true

        sheet.topCornersRadius = 16

        sheet.extendBackgroundBehindHandle = false

        present(sheet, animated: true)
```

**Comment by gordontucker** [comment]
Version 1.4.6 is no longer supported. I'd recommend updating to 2.0.0 instead, but if you'd like you can make a PR from `version-1` branch and try to fix it yourself. Feel free to open a PR if you find a fix (I fixed it in 2.0.0 by using safeAreaInsets instead, but doing that in 1.4.6 is a big chore). The problem with trying to just put a background color like some have tried is that the navigation bar can be different colors (and potentially even translucent).

**Comment by abayken** [comment]
Is version 2.0.0 stable? I noticed that it was released only several days ago. Does it have a lot of bugs?

**Comment by gordontucker** [comment]
It should be stable, but I haven't released my own apps with it quite yet. I _have_ integrated into my own production apps and don't have any issues so far, and plan to release them as soon as I finish all the prerelease testing tasks. 
You are welcome to keep using the previous version if you'd like, but it was written with some bad assumptions that prevented me from fixing them without a bigger change (your bug is one of those things).
