### ISSUE TITLE
How do I Present Fitted Sheet inline?

### ISSUE THREAD

**Issue by farrasdoko** [gordontucker/FittedSheets#89]
I read the readme.md file and found how to implement it, but it doesn't work.
I changed the constraint from: (*Use of unresolved identifier 'Constraints'*)
```
Constraints(for: sheet.view) {
    $0.edges(.top, .left, .bottom, .right).pinToSuperview()
}
```
to: (*Cannot assign to property: 'topAnchor' is a get-only property*)
```
NSLayoutConstraint.activate([
    sheetController.view.topAnchor = view.topAnchor,
    sheetController.view.bottomAnchor = view.bottomAnchor,
    sheetController.view.leadingAnchor = view.leadingAnchor,
    sheetController.view.trailingAnchor = view.trailingAnchor
])
```
I removed the constraint and directly add `sheetController.animateIn()` then nothing happened :(

**Comment by gordontucker** [comment]
It looks like you are using anchors incorrectly. Try reading up on how to use auto layout and the anchors. I am using some code to make using the anchors a bit easier, so that is another option for you to look into.

https://www.hackingwithswift.com/example-code/uikit/how-to-position-a-view-using-auto-layout-anchors 
https://useyourloaf.com/blog/batch-updating-of-constraints/

**Comment by gordontucker** [comment]
```
NSLayoutConstraint.activate([
    sheet.view.topAnchor.constraint(equalTo: self.view.topAnchor),
    sheet.view.bottomAnchor.constraint(equalTo: self.view.bottomAnchor),
    sheet.view.leadingAnchor.constraint(equalTo: self.view.leadingAnchor),
    sheet.view.trailingAnchor.constraint(equalTo: self.view.trailingAnchor)
])```
